language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"

before_script:
    - sudo apt-get install apache2
    - sudo apt-get install php5-common libapache2-mod-php5 php5-cli
